### ISSUE TITLE
There is no permission named `viewAnyRole` for guard `web` Error

### ISSUE THREAD

**Issue by Bamux** [serenysoft/nova-permissions#10]
I have a fresh Laravel (v10.1.5 with PHP v8.2.0) installation, including Nova.  I can also successfully log into the Nova backend.
When I follow your installation instructions step by step and then try to log into the Nova backend, I get the following error message.

**Spatie\Permission\Exceptions\PermissionDoesNotExist
There is no permission named `viewAnyRole` for guard `web`.**

https://flareapp.io/share/W7zRa0k7#F94

Do you have any idea what could be causing this?

**Comment by arturasfrontit** [comment]
W

> https://github.com/serenysoft/nova-permissions#database-seeding

what if we have custom names and your seeder is not suitable for us?

**Comment by leandrogehlen** [comment]
The seeder is an example only.
You should modify as you see fit

**Comment by arturasfrontit** [comment]
> The seeder is an example only. You should modify as you see fit
`
There is no permission named `viewAnyRole` for guard `web`.`

**Comment by leandrogehlen** [comment]
https://nova.laravel.com/docs/4.0/resources/authorization.html

**Comment by arturasfrontit** [comment]
> https://nova.laravel.com/docs/4.0/resources/authorization.html

Its package policies, I changed them

**Comment by arturasfrontit** [comment]
> Does not make sense to do it. It's only include these permissions in your Seeder
> 
> Please see: [d617b84](https://github.com/serenysoft/nova-permissions/commit/d617b844036fd6618cec4e871a354c3a2e519d94)

I wanted to overite `PermissionPolicy` to return false in all methods. You defined it in `NovaPermissions.php` and `AuthServiceProvider` can't overide it. I found another solution to override you file, but it would be nice to turn off it in package config

**Comment by arturasfrontit** [comment]
> if you don't want the permissions to be available, use `disablePermissions()` https://github.com/serenysoft/nova-permissions#customizations

I want use custom policies instead of yours

**Comment by buttjer** [comment]
@arturasfrontit Our solution was using a Role Policy and the default Nova way with canSeeWhen.

```php
	public function tools(): array
	{
		return [
			\Sereny\NovaPermissions\NovaPermissions::make()
				->hideFieldsFromPermission(['group'])
				->canSeeWhen('viewAnyRole', User::class),
		];
	}
```

**Comment by leandrogehlen** [comment]
ref [#34](https://github.com/serenysoft/nova-permissions/issues/34#issuecomment-1756205519)
