### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by exshapoval** [serenysoft/nova-permissions#11]
Hi

I use Laravel 10.1.5 and Nova 4.22.1 When in .env APP_ENV=local all ok But when APP_ENV=production I see error 403 after login to admin area

How I can fix it for production?

Also I install all by instruction but don't see in menu roles and permissions

**Comment by leandrogehlen** [comment]
It's not possible to determine the cause of error with the descritpion above.
Please make a repository as example and test it. If the issue to continue happening, please share the repository to try find the problem

**Comment by exshapoval** [comment]
Hi

https://github.com/exshapoval/forsupport.git

is that enough for you?
Thanks

**Comment by leandrogehlen** [comment]
Hello you need to try find the error. When you find the error please report

**Comment by exshapoval** [comment]
How I can do it? I setup by your instruction and don't see items in menu
Also I see 403 page after login if I set APP_ENV=production

**Comment by leandrogehlen** [comment]
* Log
* Debug

**Comment by leandrogehlen** [comment]
I have tested  the `production` env in my repository and it's working.
