### ISSUE TITLE
Impossible to create new role/permission using UI

### ISSUE THREAD

**Issue by AndreyGrin** [serenysoft/nova-permissions#15]
Hey, got this interesting issue. Tried to create new permission using UI and it failed. Check screenshots. Same error when I attempt to make a new role.
<img width="1042" alt="Screenshot 2023-04-06 at 11 28 40" src="https://user-images.githubusercontent.com/2453346/230320395-b65f396c-b37f-4ffc-9938-dde175949c2d.png">
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/2453346/230320782-8d0df13d-e2c2-4b9d-8ce9-0fa1df61e7d8.png">

**Comment by leandrogehlen** [comment]
I was not able to reproduce this error.
Please provide a github repository where this issue is happening.
