### ISSUE TITLE
The field Group is not showing correctly

### ISSUE THREAD

**Issue by vodnicearv** [serenysoft/nova-permissions#17]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/14403446/236808726-4c522f25-4c87-4afe-bfef-b0a078b4c31d.png">

file name is JSON object

- `laravel/framework`: v.10.9.0
- `laravel/nova`: v4.23.0

**Comment by leandrogehlen** [comment]
I have tested this issue and i can't reproduce this scenario.

![image](https://github.com/serenysoft/nova-permissions/assets/1750751/7a152615-b81c-4024-afde-1603fbf5b0a7)

Please, provide a github repository example showing the problem

**Comment by vodnicearv** [comment]
I also use `badinansoft/nova-language-switch` v1.2.0, maybe this is reason of this error.
https://github.com/badinansoft/nova-language-switch

**Comment by vodnicearv** [comment]
tried it and the error did not disappear

**Comment by leandrogehlen** [comment]
please delete the `vendor` folder

**Comment by vodnicearv** [comment]
why?

**Comment by leandrogehlen** [comment]
Because, i think that you have outdated dependencies.
Deleting the `vendor` folder and update composer, should fix your problem

**Comment by vodnicearv** [comment]
I installed nova a few weeks ago (1 or 2 weeks). And all dependencies are to latest versions.

**Comment by leandrogehlen** [comment]
Please make a github repository showing the problem
