### ISSUE TITLE
Roles&Permissions menu disappears when customize Nova menu

### ISSUE THREAD

**Issue by ProjectesFUAB** [serenysoft/nova-permissions#18]
After customizing my menu, the tool menu (Role&Premisions) disappears.

**Comment by ProjectesFUAB** [comment]
Now I've saw that in \sereny\nova-permissions\src\Http\Nova\Resource.php is defined

`$displayInNavigation = false;`

I don't know how to change the value before creating the customaized menu (other than by overwriting the code on the source file...)

**Comment by leandrogehlen** [comment]
This is the default behavior for Laravel nova 4 when you customize the menu.

It's necessary that you add the permission and role in your menu
```php
<?php

namespace App\Providers;

use Sereny\NovaPermissions\Nova\Permission;
use Sereny\NovaPermissions\Nova\Role;

class NovaServiceProvider extends NovaApplicationServiceProvider
{
    ...

    /**
     * The application menu
     *
     * @return MenuSection[]
     */
    protected function menu()
    {
        return [            
            ...

            MenuSection::make(__('Administration'), [
                MenuItem::resource(Role::class)
                MenuItem::resource(Permission::class)
            ])->icon('cog')->collapsable(),
        ];
    }
}

**Comment by ProjectesFUAB** [comment]
So sorry, but doesn't works for me until hardcoded $displayInNavigation = true;

```
MenuSection::make('Seguretat', [
   MenuItem::resource(User::class),
   MenuItem::resource(Role::class),
   MenuItem::resource(Permission::class),
])
->icon('shield-check')
->collapsable(),
```

![image](https://github.com/serenysoft/nova-permissions/assets/71957731/4a3f788b-e4b4-40d8-847a-3e70ad511ab2)

**Comment by leandrogehlen** [comment]
You can use: 
```php
MenuItem::resource(Permission::class)->canSee(fn() => true)
```

**Comment by Robertv9** [comment]
Hello,

I use your suggestion but, I got 404 when I clicked the menu item roles and permission.

**Comment by Robertv9** [comment]
Fixed imported NovaPermission in tools

     public function tools()
    {
        return [
            new \Sereny\NovaPermissions\NovaPermissions(),
        ];
    }
