### ISSUE TITLE
Tool not visible in menu

### ISSUE THREAD

**Issue by HeadStudios** [serenysoft/nova-permissions#26]
Hi, 

I have tried everything but my tool is not visible in the left menu - I know I probably did something wrong because it's showing in my live site just not on my development site - can you suggest anything to check?

![Image 2023-07-02 at 9 57 49 am](https://github.com/serenysoft/nova-permissions/assets/4220965/0ccd74c6-70d1-46d7-9ca1-cad3964b289f)
![Image 2023-07-02 at 9 58 15 am](https://github.com/serenysoft/nova-permissions/assets/4220965/0802f703-a614-45c1-8b6b-dbde26a26c5f)

Video for context:
https://share.getcloudapp.com/qGu6EP8G

Thank you!

**Comment by leandrogehlen** [comment]
Please, can you remove `canSee` to dectec if is the point of issue?

**Comment by HeadStudios** [comment]
Thank you! This has fixed the issue!
