### ISSUE TITLE
A method to add Select field to chose the role on create / update

### ISSUE THREAD

**Issue by beshoo** [serenysoft/nova-permissions#28]
As we know, we can not attach roles upon creation or updating. https://github.com/serenysoft/nova-permissions/issues/21

You need to go to attach method on the module page!

![image](https://github.com/serenysoft/nova-permissions/assets/4635115/a6dd1139-c47b-4bb9-8465-5a67134cd7ef)

**Well, I created a simple select**  while retrieving all available roles and only isSuperAdmin can see it.

```
 Select::make('Role')
                ->options(function () {
                    return \Spatie\Permission\Models\Role::pluck('name')->mapWithKeys(function ($value) {
                        return [$value => $value];
                    });
                })
                ->fillUsing(function () {
                    return null;
                })->hideFromIndex()->hideFromDetail()->resolveUsing(function ($request, $model) {
                    return $model->getRoleNames();
                })->rules('required')->canSee(function ($request) {
                   return ($request->user()->isSuperAdmin());
                }
                )
```
To update the role we need to syncRoles! **this will remove any previous role/permissions** 
and here is the afterCreate/afterUpdate

```
public static function afterCreate(NovaRequest $request, Model $model)
    {
         $model->syncRoles([$request->role]);
    }

    public static function afterUpdate(NovaRequest $request, Model $model)
    {
         $model->syncRoles([$request->role]);
    }
```

Now once you want to create/update a record
you can attach the role directly

![image](https://github.com/serenysoft/nova-permissions/assets/4635115/baf3a2fe-ff69-488b-bf06-5e822eccb16e)

**Comment by beshoo** [comment]
On the other hand, you can use https://github.com/blendbyte/nova-attach-many

**Comment by leandrogehlen** [comment]
This is a request?

If yes, it is not the pupouse of repository

**Comment by beshoo** [comment]
I'm actually helping another user to find a way to add this functionality to another resource.

**Comment by leandrogehlen** [comment]
I don't undersand.
Is not more easy add a [HasMany](https://nova.laravel.com/docs/4.0/resources/relationships.html#hasmany) relation to model?

**Comment by beshoo** [comment]
I'm not sure if I understand correctly, but using `HasMany::make('Roles')` won't provide a select option to choose from when creating or updating a user.

**Comment by beshoo** [comment]
My method is easier and will syncRoles the role on create and update..

![image](https://github.com/serenysoft/nova-permissions/assets/4635115/debd04f9-eb0f-4c2e-8e7a-f1712c310ef3)

**Comment by leandrogehlen** [comment]
If you want that a resource has just one role you should delcare a [`belongsTo`](https://laravel.com/docs/10.x/eloquent-relationships#one-to-one-defining-the-inverse-of-the-relationship) relation in your model and use [BelongsTo](https://nova.laravel.com/docs/4.0/resources/relationships.html#belongsto) in resource
