### ISSUE TITLE
Installation 'README.md' -- Database Seeding

### ISSUE THREAD

**Issue by MATTOFIRE** [serenysoft/nova-permissions#30]
Hi,

there is an error in documentation for "Publish our Seeder with the following command:"

if run - php artisan vendor:publish --provider="Sereny\NovaPermissions\ToolServiceProvider" --tag="seeders"- not find e file php.

the --tag is 'No publishable resources for tag [seeders]. ' -> the tag currect is 'seeds'.

inside ToolServiceProvider.php : 

public function boot(Filesystem $filesystem)

$this->publishes([
            __DIR__ . '/../database/seeds/RolesAndPermissionsSeeder.php.stub' => $this->app->databasePath() . "/seeds/RolesAndPermissionsSeeder.php",
        ], 'seeds');

should be corrected.

Many thanks

**Comment by MATTOFIRE** [comment]
or better. I rephrase. nel file is correct and in the documentation https://github.com/serenysoft/nova-permissions is --tag=seeders

but really seeders don't run. create a directory seeds and clearly when we run db:seed it has a dependency conflict.

**Comment by leandrogehlen** [comment]
Close  [dfea808](https://github.com/serenysoft/nova-permissions/commit/dfea808c639ff0fd8af6add1951dbbfe21d96b19)
