### ISSUE TITLE
Find bugs when using laravel octane

### ISSUE THREAD

**Issue by tomonly4work** [serenysoft/nova-permissions#33]
I currently using Laravel 9 with Octane and Swoole. 
Here are the steps:
1. Started the server using Octane.
2. Logged in as a super-admin account and created a role with certain permissions.
3. Attached the role to account B.
4. Logged in as account B, but it didn't have the expected permissions.

However, after I restarted the server, the problem was resolved.
I can attached the role to different account and works fine.

**Comment by leandrogehlen** [comment]
I have no knowledge about Laravel Octane. It seems there is an issue with [laravel-permission](https://github.com/spatie/laravel-permission/blob/main/config/permission.php#L112)

**Comment by tomonly4work** [comment]
Finally solve the problem by adding the listener.
This [issue](https://github.com/spatie/laravel-permission/issues/2322) help a lot.
