### ISSUE TITLE
Roles and permissions show up der resources as well

### ISSUE THREAD

**Issue by AndreV93** [serenysoft/nova-permissions#37]
Hey,
as described in the headline the roles and permissions also show up under the resource tab 
![Screenshot 2024-02-04 at 23 22 10](https://github.com/serenysoft/nova-permissions/assets/10657738/26d9827f-5bea-48da-b8ee-0c830a58741d)

it can be fixed by setting `public static $displayInNavigation = false;` in the Permission and Role class.
I would suggest adding that, or is there another easy way to do that?

**Comment by leandrogehlen** [comment]
https://github.com/serenysoft/nova-permissions?tab=readme-ov-file#customizations

`->disablePermissions()`

**Comment by AndreV93** [comment]
Thanks, I already tried that but sadly it didn't work for me.
`NovaPermissions::make()
                ->roleResource(Role::class)
                ->permissionResource(Permission::class)
                ->disablePermissions()`
                
setting it up like this doesn't change the visibility in the menu for me.
To verify that the configuration itself is working properly I added the 
`->hideFieldsFromRole([
                    'id',
                    'guard_name'
                ])`
                
which worked fine

**Comment by leandrogehlen** [comment]
ref serenysoft/nova-permissions@75e7737
