### ISSUE TITLE
Version 1.5 not showing permissions in custom menu

### ISSUE THREAD

**Issue by AndreV93** [serenysoft/nova-permissions#38]
Upgrading from version 1.4 to version 1.5 removes the display of permission in custom menu.

` MenuSection::make(__('RolesPermissions'), [
                   MenuItem::resource(Role::class),
                   MenuItem::resource(Permission::class)
               ])->icon('shield-check')->collapsable()`

doesn't show on the sidebar anymore.

**Comment by leandrogehlen** [comment]
https://github.com/serenysoft/nova-permissions?tab=readme-ov-file#customizations
Remove `disablePermissions()`

**Comment by AndreV93** [comment]
```
public function tools()
    {
        return [
            NovaPermissions::make()
                ->hideFieldsFromRole([
                    'id',
                    'guard_name'
                ])
        ];
    }
```

it's not configured, I assume the change of displayInNavigation=false is not compatible with custom menus...
Maybe reverting it and updating the documentation to use custom menus instead of the one that nova is creating automatically is the way to go here

**Comment by leandrogehlen** [comment]
I solved it, using: 

```php
    public function boot()
    {
        parent::boot();
    
        Nova::mainMenu(function (Request $request) {
            return $this->menu();
        });
        ...
    }
    
    /**
     * The application menu
     *
     * @return MenuSection[]
     */
    protected function menu()
    {
        return [
            MenuSection::make(__('Administration'), [
                MenuItem::resource(Role::class)->canSee(fn() => true),
                MenuItem::resource(Permission::class)->canSee(fn() => true)
            ])->icon('cog')->collapsable(),
        ];
    }
```

**Comment by AndreV93** [comment]
Thanks, works for me as well, a bit hacky but good enough :)
Maybe add this part to the documentation as well

**Comment by leandrogehlen** [comment]
Please make a PR to include it, in the docs

**Comment by AndreV93** [comment]
I would like to, but don't have permissions on the project to push anything :)

**Comment by ProjectesFUAB** [comment]
Better this way?

`MenuItem::resource(Role::class)->canSee(fn ($request) => $request->user()->can('viewAnyRole')),`

**Comment by leandrogehlen** [comment]
Please make tests using master version
ref b2e21415e652e799da721fc02155f65a3ea76576
