### ISSUE TITLE
Seeder does not have a namespace

### ISSUE THREAD

**Issue by KenHuangTW** [serenysoft/nova-permissions#41]
As the title suggests, RolesAndPermissionsSeeder.php does not include a namespace, which prevents me from using `php artisan db:seed --class=RolesAndPermissionsSeeder`.

I hope to be able to specify the Seeder for import.

**Comment by leandrogehlen** [comment]
Please, make a PR to solve it

**Comment by leandrogehlen** [comment]
ref #43
