### ISSUE TITLE
roles show up in global search

### ISSUE THREAD

**Issue by nikoo-eshratabadi** [serenysoft/nova-permissions#46]
thanks for this great package:D
I'm just wondering how i can disable the global search for it since it's not a nova resource i can't just change $globallySearchable variable. any suggestions?

**Comment by leandrogehlen** [comment]
Hello @nikoo-eshratabadi, thanks for your comment.

to disable `$globallySearchable`:

Creates `Role.php` resource in `app/Nova/`

```php 
class Role extends Sereny\NovaPermissions\Nova\Role
{
    /**
     * Indicates if the resource should be displayed in the sidebar.
     *
     * @var bool
     */
    public static $displayInNavigation = false;
}
```

in `app/Providers/NovaServiceProvider.php`

```php

use App\Nova\Role;

// ...

public function tools()
{
    return [
        // ...
        \Sereny\NovaPermissions\NovaPermissions::make()
            ->roleResource(Role::class)
        ...
}
```
