### ISSUE TITLE
Possible display issue

### ISSUE THREAD

**Issue by AndreSchwarzer** [serenysoft/nova-permissions#5]
# Issue Description

When viewing a user, the assigned role is displayed but the permissions assigned to the role seem not to be detected correctly. 

All dots are red instead of green.

### User Detail

<img width="1748" alt="user-detail-view" src="https://user-images.githubusercontent.com/6991100/213799877-9583a39b-d586-459d-bb5e-89e4c7e83b0e.png">

### Role Index/List

<img width="1775" alt="role-index-view" src="https://user-images.githubusercontent.com/6991100/213799895-e12e796f-0a90-41d1-b9c3-9753f8d1438d.png">

### Role Detail

<img width="1760" alt="role-detail-view" src="https://user-images.githubusercontent.com/6991100/213799924-e250b6b9-67f9-43c1-9323-26e587c81096.png">

**Comment by WebmasterRobe** [comment]
I also have the same issue on my project

**Comment by leandrogehlen** [comment]
I have tried to reproduce this scenario, but i can do it.

![image](https://user-images.githubusercontent.com/1750751/214618254-6741b487-1752-4eeb-984b-d882796196f0.png)

![image](https://user-images.githubusercontent.com/1750751/214618412-5293e395-79c4-4a40-ab75-684b6556deb3.png)

**Comment by WebmasterRobe** [comment]
Hi Leandro, I've just send you an invitation to see my project.

**Comment by leandrogehlen** [comment]
closed via #644b1a1

**Comment by leandrogehlen** [comment]
@WebmasterRobe, thanks for the repository
