### ISSUE TITLE
Nova 5.x compatibility

### ISSUE THREAD

**Issue by vbezruchkin** [serenysoft/nova-permissions#51]
Hello,

Thanks for your package. Any chance to support Nova 5.x? 

Thanks

**Comment by leandrogehlen** [comment]
Hello @vbezruchkin,

I'm sorry, but I do not have a license for version 5. Currently, I have replaced Nova with Filament.
If you'd like to adapt it to Nova 5, feel free to make a PR.

Thank you!

**Comment by christian-heiko** [comment]
@vbezruchkin seems the upgrade is super easy. ive tested it a bit and no issues occured. maybe you can give it a go as well and place your feedback here:

https://github.com/serenysoft/nova-permissions/pull/52

**Comment by leandrogehlen** [comment]
The PR #52 has been approved. I do not have license for Nova 5.
Please execute `npm run production` and submit a PR

**Comment by jastranlove2020** [comment]
Dear,

Thank you for your useful package. but it was outdated since Nova V5
Anyone can use the merge hash to install package compatible to V5 by issuing command
composer require sereny/nova-permissions:dev-master#22685aa

Thank you @christian-heiko for the patching.

**Comment by itrack** [comment]
Hi @leandrogehlen,
Can you please make a new tag and release with these changes?

Thank you!

**Comment by leandrogehlen** [comment]
I have approved the PR #53.
Please confirm that the changes are working, and then i will tag the new version

**Comment by itrack** [comment]
Hi @leandrogehlen , for me it works as expected, thank you!
